name: flutter_alert_package
description: An Alert Flutter package.

version: 0.0.1+1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true