name: flutteralertexample
description: Example Flutter application.
## from the terminal: "git add -f .idea/dictionaries" to port dictionary of added words like sqflite
# Paste just below 'description:'

version: 0.0.1+1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  flutter_abstract_package:
    git:
      url: https://github.com/SilversphereInc/flutter_abstract_classes.git
  flutter_alert_package:
    path: ../
  flutter_strings:
    git:
      url: https://github.com/SilversphereInc/flutter_strings.git
  flutter_theme_package:
    git:
      url: https://github.com/SilversphereInc/flutter_theme_package.git
  flutter_tracers:
    git:
      url: https://github.com/SilversphereInc/flutter_tracers.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
